-- Generated by scripts/export-runrepeat-sql.mjs. No rows are deleted.
-- Applies only to exact existing models. Any mismatch rolls back all changes.
begin;
do $patch$
declare
  review jsonb;
  changed integer;
begin
  for review in select value from jsonb_array_elements($reviews$[
  {
    "shoeId": "nike-페가수스-프리미엄",
    "brand": "Nike",
    "model": "페가수스 프리미엄",
    "reviewModel": "Nike Pegasus Premium",
    "score": 83,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/nike-pegasus-premium",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "nike-보메로-18",
    "brand": "Nike",
    "model": "보메로 18",
    "reviewModel": "Nike Vomero 18",
    "score": 90,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/nike-vomero-18",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "nike-보메로-플러스",
    "brand": "Nike",
    "model": "보메로 플러스",
    "reviewModel": "Nike Vomero Plus",
    "score": 91,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/nike-vomero-plus",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "nike-줌-플라이-6",
    "brand": "Nike",
    "model": "줌 플라이 6",
    "reviewModel": "Nike Zoom Fly 6",
    "score": 88,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/nike-zoom-fly-6",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "nike-알파플라이-3",
    "brand": "Nike",
    "model": "알파플라이 3",
    "reviewModel": "Nike Alphafly 3",
    "score": 93,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/nike-alphafly-3",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "adidas-보스턴-13",
    "brand": "Adidas",
    "model": "보스턴 13",
    "reviewModel": "adidas Adizero Boston 13",
    "score": 88,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/adidas-adizero-boston-13",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "adidas-아디오스-프로-4",
    "brand": "Adidas",
    "model": "아디오스 프로 4",
    "reviewModel": "adidas Adizero Adios Pro 4",
    "score": 93,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/adidas-adizero-adios-pro-4",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "hoka-본디-9",
    "brand": "HOKA",
    "model": "본디 9",
    "reviewModel": "HOKA Bondi 9",
    "score": 86,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/hoka-bondi-9",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "new-balance-880-v15",
    "brand": "New Balance",
    "model": "880 V15",
    "reviewModel": "New Balance Fresh Foam X 880 v15",
    "score": 82,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/new-balance-fresh-foam-x-880-v-15",
    "checkedAt": "2026-09-06",
    "verified": true
  },
  {
    "shoeId": "on-클라우드-서퍼-2",
    "brand": "On",
    "model": "클라우드 서퍼 2",
    "reviewModel": "On Cloudsurfer 2",
    "score": 80,
    "scoreKind": "overall",
    "sourceSection": "Our verdict / Our score",
    "sourceUrl": "https://runrepeat.com/on-cloudsurfer-2",
    "checkedAt": "2026-09-06",
    "verified": true
  }
]$reviews$::jsonb)
  loop
    update public.runfit_shoes
    set data = jsonb_set(data, '{runRepeatReview}', review, true), updated_at = now()
    where id = review->>'shoeId'
      and brand = review->>'brand'
      and model = review->>'model'
      and data->>'id' = review->>'shoeId'
      and data->>'brand' = review->>'brand'
      and data->>'model' = review->>'model';
    get diagnostics changed = row_count;
    if changed <> 1 then
      raise exception 'Exact model not found: %', review->>'shoeId';
    end if;
  end loop;
end;
$patch$;
commit;
